# Generated by Django 5.2.4 on 2025-08-05 02:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_message_recipient_id_message_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=uuid.uuid4, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation'),
        ),
    ]
